### ISSUE TITLE
Next Lesson button glitch?

### ISSUE THREAD

**Issue by micahlt** [ideoxan/ideoxan#11]
_The editor is looking great, by the way!_

**Describe the bug**
The text on the next and previous lesson buttons appears top aligned (vertically) when the page loads.  However, on hover they become aligned centered (again, vertically).

**To Reproduce**
1. Hover over the next button
2. The positioning is adjusted

**Expected behavior**
To be honest I don't know.  But this doesn't seem quite right... maybe the button text should be vertically centered from onload?

**Screen recording**
![ezgif-2-4366deb719d3](https://user-images.githubusercontent.com/28816297/83703449-4f94f280-a5d5-11ea-8d18-d5ee88ebca36.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS Focal Fossa
 - Browser: Chrome
 - Version 83

**Additional context**
I'll try to see what I can do here :smiley:

**Comment by Skyclo** [comment]
I believe I know what the issue is. Can you please describe your computer's resolution or the dimensions of the browser window? Do you have any page modifying extensions installed?

**Comment by micahlt** [comment]
My PC's resolution is 16:10 (1620 by 1050), and my browser window size while viewing that page was 1680 by 871.  Heh, I've got lots of extensions, but none of them were activated while on Ideoxan.

**Comment by Skyclo** [comment]
> 
> 
> My PC's resolution is 16:10 (1620 by 1050), and my browser window size while viewing that page was 1680 by 871. Heh, I've got lots of extensions, but none of them were activated while on Ideoxan.

Okay I will look into it. Most likely I have to rewrite the code for that area because of formatting issues.

**Comment by Skyclo** [comment]
Can you verify that the recent updates have gotten rid of this issue. Using your dimensions specified, I was unable to reproduce the issue.

**Comment by micahlt** [comment]
@Skyclo Fixed!
