### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by micahlt** [ideoxan/ideoxan#16]
**Describe the bug**
When visiting the instance of Ideoxan hosted on Heroku, I get a plaintext page that simply says `Internal Server Error`.

**To Reproduce**
1. Go to https://ideoxan.herokuapp.com/

**Expected behavior**
The Ideoxan editor shows up.

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1909 64-bit
 - Browser: Chrome
 - Version: 83

**Comment by Skyclo** [comment]
The issue is currently being investigated

**Comment by Skyclo** [comment]
The issue has been resolved.
