### ISSUE TITLE
Login and signup pages not redirecting to index page when logged in

### ISSUE THREAD

**Issue by ArduinoidIOT** [ideoxan/ideoxan#27]
**Describe the bug**
When logged in, the /login and /signup routes give a 404 instead of redirecting to the index page

**To Reproduce**
1. Log in
2. Scroll down to Pricing
3. Click 'Sign up'

**Expected behavior**
It should redirect to the index page

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Browser: Firefox
 - Version:  77.0.1

**Comment by Skyclo** [comment]
Can you confirm that the function `isNotAuth` found in `auth.js` (and used as middleware in the login/sign up paths) is returning true?

**Comment by ArduinoidIOT** [comment]
It should be false when logged in.

**Comment by Skyclo** [comment]
@ArduinoidIOT Are you logged into the site when this happens?

**Comment by ArduinoidIOT** [comment]
Yes

**Comment by Skyclo** [comment]
@ArduinoidIOT Okay so that's why. I intentionally prevented users from viewing the sign up and login pages when they are signed in. This is done to prevent duplicate or invalid sessions. 

However, that being said, I should remove or alter the sign up prompts in the pricing areas based on authentication status.

**Comment by ArduinoidIOT** [comment]
Um, shouldn't it redirect to the index page, that's what most people expect

**Comment by Skyclo** [comment]
@ArduinoidIOT I already have the server throw a 403 (Unauthorized) HTTP error code to anyone attempting to use the API if they are already authenticated. I will also change the HTML accepted response to redirect to the index page :+1:
