### ISSUE TITLE
Tech stack?

### ISSUE THREAD

**Issue by locness3** [ideoxan/ideoxan#3]
What will be the tech stack for this project?

**Comment by Skyclo** [comment]
Node.js, Express.js, HTML, CSS, JS (DOM), and MongoDB.

**Comment by locness3** [comment]
Why not LESS/SCSS instead of pure CSS?

**Comment by Skyclo** [comment]
I am more familiar with vanilla HTML, CSS, and DOM JS. This is one of the reasons why we decided not use React, Angular, Vue, or any other JavaScript framework. I have considered, once the site is completed, rewriting the CSS in SCSS.

**Comment by micahlt** [comment]
@Skyclo I'm with you on not using JS frameworks.  But I do think you should consider Sass, as it's hardly different that vanilla CSS.  The one feature I really use is nesting styles, which can be really handy for larger projects with non-unique class names.

**Comment by locness3** [comment]
Or LESS, which is really close to vanilla CSS.
