### ISSUE TITLE
502 error on visiting /

### ISSUE THREAD

**Issue by micahlt** [ideoxan/ideoxan#52]
**Describe the bug**
When visiting https://ideoxan.com, Cloudflare reports a 502 bad gateway error.

**To Reproduce**
1. Open https://ideoxan.com in a web browser.

**Expected behavior**
The website should appear.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Comment by Skyclo** [comment]
This is done intentionally. Every other service (email, DNS, CDN) is operational.

**Comment by micahlt** [comment]
@Skyclo wait, but why?  Is the site down for maintenance?

**Comment by Skyclo** [comment]
The website isn't done yet. It will come back soon
