### ISSUE TITLE
Fix Spacing and Alignment of Profile Settings

### ISSUE THREAD

**Issue by Skyclo** [ideoxan/ideoxan#69]
**Describe the bug**
The CSS for the settings page for signed in users is not correct. There is a small space to the right that isn't used by a `div` or `form` element. This is especially apparent with light mode enabled.

**To Reproduce**
1. `$ npm run dev`
2. Go to `127.0.0.1:3080`
3. Create account or sign in
4. Navigate to the `/settings` endpoint

**Expected behavior**
The element should take the full width of the page.

**Additional context**
The user settings needs a massive overhaul but this should be a temporary fix until then.

**Comment by guidimas** [comment]
Hello, I would like try helping you with this one for Hacktoberfest! May you assign it to me? Thank you.

**Comment by Skyclo** [comment]
> 
> 
> Hello, I would like try helping you with this one for Hacktoberfest! May you assign it to me? Thank you.

Done!

**Comment by guidimas** [comment]
Hello @Skyclo,

Quick question about the expected behavior on smaller screens, should the sections (Update Display Name, Email and Password) be divided into new lines to fit the screen size, or should they always be on the same line, no matter the size of the screen?

Thank you.

**Comment by Skyclo** [comment]
> 
> 
> Hello @Skyclo,
> 
> Quick question about the expected behavior on smaller screens, should the sections (Update Display Name, Email and Password) be divided into new lines to fit the screen size, or should they always be on the same line, no matter the size of the screen?
> 
> Thank you.

Since you are the one making the changes, feel free to go with your gut and choose whichever one you think is best. However, I will say that wrapping each section on to a new line (on smaller displays) would probably be best. Flex wrap would be the easiest way to do this CSS wise.

Just keep in mind the current layout of the settings page was something I threw together in under an hour 😄

**Comment by Aagam-Jain-113** [comment]
Hello I would like to contribute....Can u assign it to me?

**Comment by Skyclo** [comment]
> Hello I would like to contribute....Can u assign it to me?

Sorry, I believe this issue is already being worked on by another contributor. If you'd still like to contribute, you can either try and work with @guidimas or you can work on another issue. I will be posting more issues that can be tackled today and throughout next week.
