### ISSUE TITLE
Editor and Website Relocation

### ISSUE THREAD

**Issue by Skyclo** [ideoxan/ideoxan#70]
**Is your feature request related to a problem? Please describe.**
The root directory (`./`) is extremely cluttered and should be cleaned up.

**Describe the solution you'd like**
The `./editor/` and `./www/` directories should be moved into a new subdirectory (`./pages/` or `./content/` for example).

**Describe alternatives you've considered**
The Website (`./www/`) can be moved into a seperate github repository all together and used as a submodule. However, this is more complicated and could have much more implications than just keeping it localized.

**Additional context**
Due to the fact that the editor (@[koala](https://github.com/ideoxan/koala)) is a submodule, it will have to be removed then added back under a different directory. The global server configuration will also need to be edited to the new directory for the editor & website files. While there is no documentation on the server just yet, this should be fairly simple to do.

**Comment by StephanieGreenberg** [comment]
I can work on this!
