### ISSUE TITLE
Website Translation

### ISSUE THREAD

**Issue by Skyclo** [ideoxan/ideoxan#74]
**Is your feature request related to a problem? Please describe.**
At this point in time, the website is only in English. Those who have English as a second language or who do not speak it at all can have a hard time navigating and understanding the website contents. While website translation services are available (ie. Google Translate, Microsoft Translate, Yandex Translate), these can sometimes be inaccurate and hard to use.

**Describe the solution you'd like**
The website should be translated from English (US) into major languages. These might include Spanish, French, German, Russian, Mandarin, Hindi, etc. **THIS ISSUE IS ONLY FOR TRANSLATING THE WEBSITE/DOCS. SEPARATE ISSUES WILL BE CREATED FOR THE EDITOR AND COURSES** 

**Assignments**
Due to the limitation on 10 assignments on GitHub, the following will be a running list of assignments to specific languages. There can be more than 1 language assigned to a person. There can also be more than 1 person assigned to a language. The following is an updated list of assignments:
- Hindi: @ArduinoidIOT 
- Spanish: @brunocerecetto, @MigueMartelo
- Swedish: @Martinnord
- Indonesian: @ilhamm24
- German: @SmuSmu ✅
- French: @locness3 ✅
- Portuguese: @EBethus, @eriqueduarte (BR)
- Turkish: @Yutyo ✅
- Mandarin: _None_
- Russian: _None_
- _More to come with suggestions_

*(✅ = Completed)*

**Comment by Skyclo** [comment]
I suggest that no one starts since I have to implement a translation and localization system in the website.

**Comment by brunocerecetto** [comment]
I can translate to Spanish 🤚🏻

**Comment by Skyclo** [comment]
> I can translate to Spanish 🤚🏻

Okay, great! You've been added. I will let everyone know when the repository is ready to be translated.

**Comment by Martinnord** [comment]
I can do it in Swedish if you'd like ✌️

**Comment by Skyclo** [comment]
> 
> 
> I can do it in Swedish if you'd like ✌️

Added!

**Comment by MigueMartelo** [comment]
> I can translate to Spanish 🤚🏻

Can I help you to traslate to spanish?

**Comment by brunocerecetto** [comment]
> > I can translate to Spanish 🤚🏻
> 
> @brunocerecetto Can I help you to traslate to spanish?

@MigueMartelo sure! no Problem!

**Comment by Skyclo** [comment]
> 
> 
> > I can translate to Spanish 🤚🏻
> 
> @brunocerecetto Can I help you to traslate to spanish?

Added! Be sure to coordinate on who does what... well, not right now considering I still have to implement translation features 😄

**Comment by ilhamm24** [comment]
I can translate into Indonesian

**Comment by SmuSmu** [comment]
I can take care of german

**Comment by Skyclo** [comment]
@ilhamm24 @SmuSmu added!

**Comment by locness3** [comment]
I can do French!

**Comment by Skyclo** [comment]
> 
> 
> I can do French! It's my first language ;)

Added!

**Comment by Skyclo** [comment]
Hello @ArduinoidIOT, @brunocerecetto, @MigueMartelo, @Martinnord, @ilhamm24, @SmuSmu and @locness3. I know it has been a while since I published the issue, but PR #99 was just merged. This added functionality for website translation. The main part of the website (ie. home page, about page, login, etc.) have all been modified to support different languages. 🎉 

If you still wish to work on the language you claimed, there are files for each language under `./content/www/locales/`. All of them, with the exception of Spanish, have been filled in with the **English** translation of the website. I have done this so each one of you can simply edit your respective files by translating the original content. 

Keep in mind we will also need translators later for the editor (which there isn't really much to translate) and the Courses (which again, will take time to implement).

Good luck! If anyone needs anything, don't be hesitant to reach out! 👍 

** **

*For @brunocerecetto and @MigueMartelo: you two just have to verify my ~~horrible~~ translation. Most likely, you will find a lot of errors due to the fact that my only experience with the language is from my classes in high school.* 🤣

**Comment by EBethus** [comment]
I shall add protugues transltation

**Comment by Skyclo** [comment]
> I shall add protugues transltation

Added! Be sure to add a `pt.json` under `./content/www/locales/`, add `pt` to the list of default accepted locales, and add the language to the language switcher in the footer!

**Comment by eriqueduarte** [comment]
I can add do PT-BR

**Comment by EBethus** [comment]
@eriqueduarte  I have a partial translation, I would upload and you could help me to finish it.

**Comment by Skyclo** [comment]
> I can add do PT-BR

Since I don't know Portuguese, I have a question. Is there a need for distinction between the different dialects? Is `PT-BR` similar to `PT` to where people can understand both (similar to how people can understand both `EN-US` and `EN-GB`)?

**Comment by EBethus** [comment]
@SmuSmu it's like En-GB and EN-US, Portuguese and Brazilians can understand both, but there are more difference than British and American English.

**Comment by Skyclo** [comment]
> 
> 
> it's like En-GB and EN-US, Portuguese and Brazilians can understand both, but there are more difference than British and American English.

Gotcha. Adding @eriqueduarte

**Comment by SmuSmu** [comment]
Can someone merge my pr? October ist almost over

**Comment by EBethus** [comment]
@eriqueduarte I did a PR with a partial translation
