### ISSUE TITLE
Default Config File

### ISSUE THREAD

**Issue by Skyclo** [ideoxan/ideoxan#75]
**Is your feature request related to a problem? Please describe.**
It is bad practice not to have a default config file. Also, secrets can not be stored in its current state. 

**Describe the solution you'd like**
Make the current configuration file a default one (ie. change to `config.default.json`) and have that as a fall back if there is no `config.json` available. Also blacklist `config.json` but not `config.default.json` in `.gitignore` so that secrets can be placed in the config file. This will reduce dependency on the environment variables and make customization easier.

**Describe alternatives you've considered**
Environment variables are out of the question at this point and a transition to a blacklisted config file would be easier to read and edit.

**Comment by fuzzmz** [comment]
@Skyclo, can I get this issue assigned to myself?
