### ISSUE TITLE
Redo the User Dropdown

### ISSUE THREAD

**Issue by Skyclo** [ideoxan/ideoxan#76]
**Is your feature request related to a problem? Please describe.**
The drop down menu for signed in users is extremely buggy, horribly formatted, and an overall eyesore. 

**Describe the solution you'd like**
The menu should be redone to fit the style of the rest of the website. Maybe make it look like a css button but with a downward chevron and fit the width of the menu. It doesn't have too look this way, it was only a suggestion. Whoever decides to take this on will have full creative direction, so feel free to do what fits.

**Comment by Tudwall** [comment]
I'd like to try fixing that issue.
