### ISSUE TITLE
Split up testing files

### ISSUE THREAD

**Issue by Skyclo** [ideoxan/ideoxan#78]
**Is your feature request related to a problem? Please describe.**
In its current state, the testing scripts (`/tests/routes.test.js`) are all lumped up together in one big file. This is unorganized and can be difficult to edit/maintain testing.

**Describe the solution you'd like**
The routes should be split up based on the type of route. For example there is one file for the general routes (like `/index`, `/about`, and `/signup`), one file for the API (like `/api/v1/user/create`, and `/api/v1/user/update`), one for static routes (like `/static/*` or `/editor/static/*`), and one for editor routes (like `/editor/tutorial/000/000`). This will make the tests cleaner and more organized.

**Comment by Anirudhkarnam** [comment]
@Skyclo , Can you assign this issue to me. 
if the path to be tested is /about should the test file be /tests/about.test.js ?

**Comment by Skyclo** [comment]
> @Skyclo , Can you assign this issue to me. 
> if the path to be tested is /about should the test file be /tests/about.test.js ?

Assigned! The issues should be broken up according to the file structure under `/src/routes/` (so 2 files: api.test.js for server API tests and general.test.js for all of the routes listed in the general routes folder). 

Hope that makes sense! Don't be afraid to contact us here or on our Discord!
